routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function (){
    $shopping_items = \App\ShoppingItem::whereStatus('Active')
        ->get();

    return view('welcome', compact('shopping_items', $shopping_items));
});
Route::get('/about-us', function (){
    return view('about');
});
Route::get('/contact-us', function (){
    return view('contact');
});
Route::get('/locate-us', function (){
    return view('locate');
});
/*
 * AUTHENTICATION ROUTES
 * */
Auth::routes();
Route::get('/register/confirm/{token}', 'Auth\RegisterController@confirmEmail');
Route::get('/login/{network}', 'Auth\SocialAccountController@redirectToProvider');
Route::get('/callback/{network}/', 'Auth\SocialAccountController@callback');
Route::any('/transactions/check', 'PaymentController@checkPayments');


Route::any('/cart/add/{id}', 'ShoppingCartController@addToCart');
Route::any('/cart/item/{id}', 'ShoppingCartController@viewItem');
Route::any('/cart/remove/{id}', 'ShoppingCartController@removeItem');
Route::any('/cart/update/{id}', 'ShoppingCartController@updateItem');
Route::any('/my-cart', 'ShoppingCartController@cartIndex');
Route::any('/checkout', 'ShoppingCartController@checkoutIndex');
Route::any('/cart/order', 'ShoppingCartController@createOrder');
Route::get('/shopping/payments', 'ShoppingCartController@paymentsIndex');


/*
 * Categories Routes
 * */
Route::get('/category/cough', 'CategoriesController@getCough');
Route::get('/category/pain-management', 'CategoriesController@getPainManagement');
Route::get('/category/wound-management', 'CategoriesController@getWoundManagement');
Route::get('/category/skin-conditions', 'CategoriesController@getSkinConditions');
Route::get('/category/oral-care', 'CategoriesController@getOralCare');
Route::get('/category/medical-consumables', 'CategoriesController@getMedicalConsumables');


Route::get('/category/nutritional', 'CategoriesController@getNutritional');
Route::get('/category/baby', 'CategoriesController@getBaby');
Route::get('/category/sports-nutrition', 'CategoriesController@getSportsNutrition');
Route::get('/category/vitamins', 'CategoriesController@getVitamins');
Route::get('/category/herbal', 'CategoriesController@getHerbal');
Route::get('/category/pregnancy', 'CategoriesController@getPregnancy');


Route::get('/category/body-skin-care', 'CategoriesController@getBodySkinCare');
Route::get('/category/deodorant', 'CategoriesController@getDeodorant');
Route::get('/category/hair-care', 'CategoriesController@getHairCare');
Route::get('/category/make-up', 'CategoriesController@getMakeUp');
Route::get('/category/sun-protection', 'CategoriesController@getSunProtection');


Route::get('/category/nappies', 'CategoriesController@getNappies');
Route::get('/category/baby-feeding', 'CategoriesController@getBabyFeeding');

Route::get('/payments/shopping/{id}', 'ShoppingCartController@returnUrl');
Route::get('/paynow/result/shopping/{id}', 'PaynowController@resultUrl');
Route::get('/paynow/check', 'ShoppingCartController@checkPayments');

Route::any('/paypal/express', 'PayPalController@expressCheckout');
Route::any('/paypal/payment/success', 'PayPalController@expressCheckoutSuccess');


/*
 * VIEW ROUTES
 * */
Route::group(['middleware' => 'auth'], function (){
    Route::post('/register/mobile', 'DetailsController@updateMobile');
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/privacy', 'HomeController@index')->name('home');
    Route::get('/payments', 'PaymentController@index')->name('payments');
    Route::get('/delivery-notes', 'DeliveryNoteController@index')->name('delivery-notes');
    Route::get('/quotes', 'QuotationController@index')->name('quotes');
    Route::get('/profile', 'PaymentController@index')->name('profile');

    Route::any('/menu/data', 'MenuController@getMenuData');
    Route::any('/menu/template', 'MenuController@getTemplate');


    /*
     * Enquiries
     * */
    Route::post('/enquiry/create', 'EnquiryController@create')->name('create_enquiry');
    Route::any('/enquiries/get', 'EnquiryController@getEnquiries')->name('get_enquiries');
    Route::get('/enquiry/add', 'EnquiryController@viewAdd')->name('add_enquiry');
    Route::post('/enquiry/update', 'EnquiryController@update')->name('update_enquiry');
    Route::any('/enquiry/delete/media', 'EnquiryController@deleteMedia')->name('delete_enquiry_media');
    Route::get('/enquiry/{id}', 'EnquiryController@viewEnquiry')->name('view_enquiry');

    /*
     * Quotations
     * */
    Route::any('/quotation/file', 'QuotationController@saveDocument');
    Route::any('/quotation/{id}', 'QuotationController@viewQuotation');
    Route::any('/quotation', 'QuotationController@generateQuotation');
    Route::any('/quotations/get', 'QuotationController@getQuotations');


    /*
     * Orders
     * */
    Route::get('/orders', 'OrderController@index')->name('orders');
    Route::post('/order/create', 'OrderController@create');
    Route::any('/order/{id}', 'OrderController@viewOrder');


    /*
     * Invoices
     * */
    Route::get('/invoices', 'InvoiceController@index')->name('invoices');
    Route::any('/invoice/{id}', 'InvoiceController@viewInvoice');
    Route::any('/invoice', 'InvoiceController@generateInvoice');
    Route::any('/invoices/get', 'InvoiceController@getInvoices');


    /*
     * Paynow,PayPal & Payments
     * */
    Route::get('/payments/{id}', 'PaynowController@returnUrl');
    Route::get('/paynow/result/{id}', 'PaynowController@resultUrl');
    Route::any('/paynow/initiate', 'PaynowController@initiate');





    Route::any('/payment/{id}', 'PaymentController@viewPayment');
    Route::get('/accept/cash', 'PaymentController@acceptPayment');
    Route::get('/accept/medical-aid', 'PaymentController@acceptMedicalAidPayment');

    /*
     * Delivery Notes
     * */
    Route::any('/delivery-note/sent', 'DeliveryNoteController@generateSentDeliveryNote');
    Route::any('/delivery-note/{id}', 'DeliveryNoteController@viewDeliveryNote');
    Route::any('/confirm-delivery', 'DeliveryNoteController@updateDelivery');


});

app/Enquiry.php
<?php

namespace App;

use App\Traits\Uuids;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\HasMedia\Interfaces\HasMedia;
use Spatie\MediaLibrary\HasMedia\Interfaces\HasMediaConversions;
use Spatie\MediaLibrary\Media;

class Enquiry extends Model implements HasMediaConversions
{
    use HasMediaTrait, Uuids;

    protected $guarded = [];

   /* public function getCreatedAtAttribute($value){
        return Carbon::parse($value)->diffForHumans();
    }
    public function getUpdatedAtAttribute($value){
        return Carbon::parse($value)->diffForHumans();
    }*/
    public function registerMediaConversions(Media $media = null)
    {
        $this->addMediaConversion('thumb')
            ->width(368)
            ->height(232)
            ->nonQueued();
    }

    public function user(){
        return $this->belongsTo(User::class);
    }
}

app/Order.php
<?php

namespace App;

use App\Traits\Uuids;
use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    use Uuids;
    protected $guarded = [];
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use App\Enquiry;
use App\Order;
use App\Quotation;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class OrderController extends Controller
{
    public function index(){
        $orders = Order::whereUserId(Auth::user()->id)
            ->paginate(10);

        return view('orders.orders', compact('orders', $orders));
    }

    public function create(Request $request){
        DB::beginTransaction();
        try {
            Order::create([
                'user_id'           => Auth::user()->id,
                'quotation_id'      => $request->quotation_id,
                'enquiry_id'        => $request->enquiry_id,
                'invoicing_address' => $request->invoicing_address,
                'delivery_address'  => $request->delivery_address,
                'delivery_method'   => $request->delivery_method,
                'contact_person'    => $request->contact_person,
                'contact_number'    => $request->contact_number,
            ]);
            $enquiry = Enquiry::find($request->enquiry_id);
            $quotation = Quotation::find($request->quotation_id);

            $enquiry->status = 'Order Placed';
            $quotation->status = 'Order Placed';

            $enquiry->save();
            $quotation->save();
            DB::commit();


            return redirect()->back()->with(['status' => 'Order Placed Successfully']);
        } catch (\Exception $exception) {
            DB::rollback();

            Log::debug($exception->getMessage());

            return redirect()->back()
                ->with(['error' => 'Order could not be placed. Please try again!']);
        }


    }

    public function viewOrder($id){
        $order = Order::whereId($id)
            ->whereUserId(Auth::user()->id)
            ->first();
        $enquiry = Enquiry::find($order->enquiry_id);
        $quotation = Quotation::find($order->quotation_id);
        $data = array('order'     => $order,
                      'enquiry'   => $enquiry,
                      'quotation' => $quotation);


        if (empty($order)) {
            abort(404);
        };

        return view('orders.order')->with($data);
    }


}

resources/views/orders/order.blade.php
@extends('layouts.app')
@section('styles')
    <style>
        .pagination {
            display: inline-flex;
            margin: 0 auto;
        }
    </style>

@endsection
@section('content')
    @include('partials.home_menu.menu')
    <div class="col-sm-12">
        <div class="card-large card-default card-body" ng-controller="orderCtrl">
            <div><h3 class="blue-text"><img src="{{asset('css/clipboards/svg/008-clipboards-7.svg')}}" alt="clipboard"
                                            width="5%"> Order - #{{$order->id}}({{$order->status}})</h3>
                <input type="hidden" name="quotation_id" id="quotation_id" value="{{$quotation->id}}">
                <input type="hidden" name="order_id" id="order_id" value="{{$order->id}}">
                <span class="right"><button style="margin-right: 10px;" class="btn blue white-text" ng-click="generateQuotation()">View Quotation</button>
                      {{--TODO: ADD Viewing invoices--}}
                {{--@if($order->status == 'Invoice Sent')
                        <button style="margin-right: 10px;" class="btn red white-text" ng-click="generateInvoice()">View Invoice</button>
                @endIf--}}
                </span>
            </div>
            <br>
            Created {{\Carbon\Carbon::parse($order->created_at)->format('d M Y')}}
            <br>
            <hr>

            <h3 class="blue-text">Enquiry #{{$enquiry->id}}</h3>
            {{$enquiry->name}}<br>
            Created {{Carbon\Carbon::parse($enquiry->created_at)->format('d M Y')}}<br>
            <b>Status</b> - {{$enquiry->status}}<br>
            <b>Description</b> - {{$enquiry->description}}
        </div>
        <br><br>
    </div>

@endsection

resources/views/orders/orders.blade.php
@extends('layouts.app')

@section('content')
    @include('partials.home_menu.menu')
    <div class="col-sm-12">
        <div class="card-large card-default card-body">
            <h3 class="left"><img src="{{asset('css/clipboards/svg/008-clipboards-7.svg')}}" alt="clipboard"
                                  width="20%">
                Orders </h3>
            <br><br><br>
            <table class="table table-hover table-bordered table-responsive{-sm|-md|-lg|-xl}">
                <caption>Double Click to View More Details</caption>
                <thead>
                <tr>
                    <th>
                        Order Number
                    </th>
                    <th>
                        Quotation Number
                    </th>
                    <th>
                        Enquiry Number
                    </th>
                    <th>
                        Status
                    </th>
                    <th>
                        Created At
                    </th>
                    <th>
                        Updated At
                    </th>
                </tr>
                </thead>
                <tbody>
                @foreach($orders as $order)
                    <tr class="clickable" ondblclick="window.location='{{url("/order/$order->id")}}'">
                        <td>{{$order->id}}</td>
                        <td>{{$order->enquiry_id}}</td>
                        <td>{{$order->quotation_id}}</td>
                        <td>{{$order->status}}</td>
                        <td>{{\Carbon\Carbon::parse($order->created_at)->diffForHumans()}}</td>
                        <td>{{\Carbon\Carbon::parse($order->updated_at)->diffForHumans()}}</td>
                    </tr>
                @endforeach

                </tbody>


            </table>
            <br>
            <div class="text-center">
                {{$orders->links()}}
            </div>

        </div>
        <br><br>

    </div>

@endsection